# Generated by Django 4.2.5 on 2023-09-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("useless", "0002_chef_position_chef"),
    ]

    operations = [
        migrations.CreateModel(
            name="RandomTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
        ),
    ]
