# Generated by Django 4.2.5 on 2023-09-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("useless", "0003_randomtable"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="random_table",
            field=models.ManyToManyField(to="useless.randomtable"),
        ),
    ]
