# Generated by Django 4.2.5 on 2023-10-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("useless", "0004_position_random_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="position",
            name="chef",
        ),
        migrations.RemoveField(
            model_name="position",
            name="random_table",
        ),
        migrations.DeleteModel(
            name="Chef",
        ),
        migrations.DeleteModel(
            name="Position",
        ),
        migrations.DeleteModel(
            name="RandomTable",
        ),
    ]
